"""Task 10 AI contracts; deliberately separate from persistence schemas."""

from __future__ import annotations

from typing import Annotated, Any
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    field_validator,
)

NonEmpty = Annotated[str, StringConstraints(min_length=1, pattern=r"\S")]
Confidence = Annotated[float, Field(ge=0.0, le=1.0, allow_inf_nan=False, strict=True)]


class MemoryCard(BaseModel):
    """Seven-field input. Caller must supply cards for this learner only."""

    model_config = ConfigDict(extra="forbid")

    card_id: NonEmpty
    meeting_id: NonEmpty | None = None
    metric_key: NonEmpty
    content: NonEmpty
    rationale: str
    tags: list[NonEmpty]
    created_at: AwareDatetime

    @field_validator("card_id", "meeting_id", mode="before")
    @classmethod
    def normalize_uuid(cls, value: Any) -> Any:
        """Accept UUID objects as well as nonempty string identifiers."""
        return str(value) if isinstance(value, UUID) else value


class MetricDraft(BaseModel):
    """Only these two fields are generated by the model for a target metric."""

    model_config = ConfigDict(extra="forbid")
    summary: NonEmpty
    confidence: Confidence


class ProfileMetric(MetricDraft):
    """Consolidated evidence summary plus IDs managed exclusively by Python."""

    model_config = ConfigDict(extra="allow")
    evidence_ids: list[NonEmpty] = Field(default_factory=list)


class LearnerProfile(BaseModel):
    """AI profile state; preserve supplied identity/metadata without inventing it."""

    model_config = ConfigDict(extra="allow")
    metrics: dict[NonEmpty, ProfileMetric] = Field(default_factory=dict)


class ProfileUpdateInput(BaseModel):
    """A null/empty baseline and recently tagged cards for one learner."""

    model_config = ConfigDict(extra="forbid")
    previous_profile: LearnerProfile | None = None
    memory_cards: list[MemoryCard] = Field(default_factory=list)
