import base64
import json
import urllib.request
from typing import Any

from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import chain

from src.app.core.config import (
    API_URL,
    DEFAULT_MODEL,
    GOOGLE_API_KEY,
    GOOGLE_IMAGE_MODEL,
    PNG_SIGNATURE,
)
from src.app.schemas.models import (
    Theme,
    VisualizationFormat,
    VisualizationResponse,
    get_theme,
)

IMAGE_PROMPT_TEMPLATE = PromptTemplate.from_template(
    "{prompt}\n\nCreate a clean conceptual illustration using this "
    "color palette: primary {primary}, secondary {secondary}, "
    "accent {accent}, background {background}."
)


def _failure(model: str, error: str) -> VisualizationResponse:
    return VisualizationResponse(
        success=False,
        format=VisualizationFormat.PNG,
        commentary="No illustration was generated.",
        metadata={"provider": "google", "model": model},
        error=error,
    )


def _first_image(payload: dict[str, Any]) -> tuple[str, bytes, str]:
    texts: list[str] = []
    for candidate in payload.get("candidates") or []:
        for part in (candidate.get("content") or {}).get("parts") or []:
            if part.get("text"):
                texts.append(str(part["text"]))
            inline = part.get("inlineData")
            if inline and inline.get("data"):
                data = base64.b64decode(inline["data"], validate=True)
                mime_type = str(inline.get("mimeType") or "image/png")
                return mime_type, data, " ".join(texts)
    raise ValueError("Response did not contain an image.")


@chain
def concept_image_chain(inputs: dict[str, Any]) -> VisualizationResponse:
    """LangChain chain that queries Google Gemini for a themed concept illustration."""
    prompt = str(inputs.get("prompt") or "")
    theme_arg = inputs.get("theme")
    timeout = float(inputs.get("timeout", 60.0))

    # Resolve configuration dynamically so monkeypatching during tests is respected
    model_override = globals().get("GOOGLE_IMAGE_MODEL")
    default_model = globals().get("DEFAULT_MODEL") or DEFAULT_MODEL
    current_model = (
        model_override if model_override is not None else GOOGLE_IMAGE_MODEL
    ) or default_model
    current_model = str(current_model).strip() or default_model
    current_api_key = (
        globals().get("GOOGLE_API_KEY")
        if "GOOGLE_API_KEY" in globals()
        else GOOGLE_API_KEY
    )
    current_api_key = (current_api_key or "").strip()
    current_api_url = globals().get("API_URL") or API_URL
    current_png_signature = globals().get("PNG_SIGNATURE") or PNG_SIGNATURE

    if not prompt.strip():
        return _failure(current_model, "An image prompt is required.")
    if not current_api_key:
        return _failure(current_model, "GOOGLE_API_KEY is not configured.")

    colors = get_theme(theme_arg)
    styled_prompt = IMAGE_PROMPT_TEMPLATE.format(
        prompt=prompt.strip(),
        primary=colors.primary,
        secondary=colors.secondary,
        accent=colors.accent,
        background=colors.background,
    )

    body = {
        "contents": [{"parts": [{"text": styled_prompt}]}],
        "generationConfig": {"responseModalities": ["TEXT", "IMAGE"]},
    }
    request = urllib.request.Request(
        current_api_url.format(model=current_model),
        data=json.dumps(body).encode("utf-8"),
        headers={"Content-Type": "application/json", "x-goog-api-key": current_api_key},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
        mime_type, asset, model_text = _first_image(payload)
    except Exception:
        return _failure(
            current_model,
            "Google image generation failed, timed out, or returned no image.",
        )

    if not asset.startswith(current_png_signature):
        return _failure(
            current_model,
            f"Google returned {mime_type[:40]}, but only PNG images are supported.",
        )

    commentary = (
        f"Conceptual illustration generated by Google {current_model} for: "
        f"{prompt.strip()[:200]}. It is illustrative only and does not represent "
        "learner data."
    )
    if model_text:
        commentary += f" Model note: {model_text[:300]}"

    return VisualizationResponse(
        success=True,
        format=VisualizationFormat.PNG,
        asset=asset,
        commentary=commentary,
        metadata={
            "provider": "google",
            "model": current_model,
            "content_type": mime_type,
            "theme": colors.model_dump(),
        },
    )


def generate_concept_image(
    prompt: str,
    theme: Theme | None = None,
    timeout: float = 60.0,
) -> VisualizationResponse:
    """Ask Gemini for an illustration styled with the theme via LangChain."""
    return concept_image_chain.invoke(
        {"prompt": prompt, "theme": theme, "timeout": timeout},
        config={
            "run_name": "google_concept_image_generator",
            "metadata": {
                "agent": "visualizer",
                "provider": "google",
            },
            "tags": ["visualizer", "google-image", "concept-art"],
        },
    )


__all__ = [
    "API_URL",
    "GOOGLE_API_KEY",
    "GOOGLE_IMAGE_MODEL",
    "IMAGE_PROMPT_TEMPLATE",
    "PNG_SIGNATURE",
    "concept_image_chain",
    "generate_concept_image",
]
