"""Google Gemini image generation for conceptual/illustrative assets.

Uses the Gemini API REST endpoint (models.generateContent) through the
standard library, so no extra SDK dependency is needed. Every failure is
returned as an unsuccessful VisualizationResponse instead of being raised.
"""

from __future__ import annotations

import base64
import json
import urllib.request
from typing import Any

from src.app.core.config import GOOGLE_API_KEY, GOOGLE_IMAGE_MODEL
from src.app.models.visualizer import (
    Theme,
    VisualizationFormat,
    VisualizationResponse,
    get_theme,
)

DEFAULT_MODEL = "gemini-3.1-flash-image"
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
API_URL = (
    "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
)


def _failure(model: str, error: str) -> VisualizationResponse:
    return VisualizationResponse(
        success=False,
        format=VisualizationFormat.PNG,
        commentary="No illustration was generated.",
        metadata={"provider": "google", "model": model},
        error=error,
    )


def _first_image(payload: dict[str, Any]) -> tuple[str, bytes, str]:
    texts: list[str] = []
    for candidate in payload.get("candidates") or []:
        for part in (candidate.get("content") or {}).get("parts") or []:
            if part.get("text"):
                texts.append(str(part["text"]))
            inline = part.get("inlineData")
            if inline and inline.get("data"):
                data = base64.b64decode(inline["data"], validate=True)
                mime_type = str(inline.get("mimeType") or "image/png")
                return mime_type, data, " ".join(texts)
    raise ValueError("Response did not contain an image.")


def generate_concept_image(
    prompt: str,
    theme: Theme | None = None,
    timeout: float = 60.0,
) -> VisualizationResponse:
    """Ask Gemini for an illustration styled with the theme (Sprints by default)."""
    model = (GOOGLE_IMAGE_MODEL or "").strip() or DEFAULT_MODEL
    if not prompt.strip():
        return _failure(model, "An image prompt is required.")
    api_key = (GOOGLE_API_KEY or "").strip()
    if not api_key:
        return _failure(model, "GOOGLE_API_KEY is not configured.")

    colors = get_theme(theme)
    styled_prompt = (
        f"{prompt.strip()}\n\nCreate a clean conceptual illustration using this "
        f"color palette: primary {colors.primary}, secondary {colors.secondary}, "
        f"accent {colors.accent}, background {colors.background}."
    )
    body = {
        "contents": [{"parts": [{"text": styled_prompt}]}],
        "generationConfig": {"responseModalities": ["TEXT", "IMAGE"]},
    }
    request = urllib.request.Request(
        API_URL.format(model=model),
        data=json.dumps(body).encode("utf-8"),
        headers={"Content-Type": "application/json", "x-goog-api-key": api_key},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
        mime_type, asset, model_text = _first_image(payload)
    except Exception:
        return _failure(
            model, "Google image generation failed, timed out, or returned no image."
        )
    if not asset.startswith(PNG_SIGNATURE):
        return _failure(
            model,
            f"Google returned {mime_type[:40]}, but only PNG images are supported.",
        )

    commentary = (
        f"Conceptual illustration generated by Google {model} for: "
        f"{prompt.strip()[:200]}. It is illustrative only and does not represent "
        "learner data."
    )
    if model_text:
        commentary += f" Model note: {model_text[:300]}"
    return VisualizationResponse(
        success=True,
        format=VisualizationFormat.PNG,
        asset=asset,
        commentary=commentary,
        metadata={
            "provider": "google",
            "model": model,
            "content_type": mime_type,
            "theme": colors.model_dump(),
        },
    )
