
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    env:
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Neo4j secret
        run: |
          if [ -z "$NEO4J_PASSWORD" ]; then
            echo "NEO4J_PASSWORD is NOT available"
            exit 1
          else
            echo "NEO4J_PASSWORD is available"
          fi

      - name: Build Docker services
        run: |
          docker compose build

      - name: Run Ruff
        run: |
          docker compose run --rm api ruff check .

      - name: Check Black formatting
        run: |
          docker compose run --rm api black --check .

      - name: Run MyPy
        run: |
          docker compose run --rm api mypy src

      - name: Run Pytest
        run: |
          docker compose run --rm api pytest

